### ISSUE TITLE
The crate requires extra privileges to run on Windows

### ISSUE THREAD

**Issue by mrowqa** [CraneStation/wasi-common#36]
Hi,

I was following [this tutorial](https://github.com/CraneStation/wasmtime/blob/master/docs/WASI-tutorial.md) and the wasmtime was crashing:

```
$ RUST_BACKTRACE=1 cargo run --bin wasmtime -- --dir=tmp ~/repos/wasi-demo/target/wasm32-wasi/debug/wasi-demo.wasm tmp/a.txt tmp/b.txt
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running `target\debug\wasmtime.exe --dir=tmp 'C:/Users/Artur Jamro/repos/wasi-demo/target/wasm32-wasi/debug/wasi-demo.wasm' tmp/a.txt tmp/b.txt`thread 'main' panicked at 'can determine file access rights: UnknownError', src\libcore\result.rs:999:5
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\sys\windows\backtrace\mod.rs:95
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\sys\windows\backtrace\mod.rs:82
   2: std::sys_common::backtrace::_print
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::print
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\sys_common\backtrace.rs:59
   4: std::panicking::default_hook::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:197
   5: std::panicking::default_hook
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:474
   7: std::panicking::continue_panic_fmt
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:381
   8: std::panicking::rust_begin_panic
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:308
   9: core::panicking::panic_fmt
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libcore\panicking.rs:85
  10: core::result::unwrap_failed<winx::winerror::WinError>
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\src\libcore\macros.rs:18
  11: core::result::Result<u32, winx::winerror::WinError>::expect<u32,winx::winerror::WinError>
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\src\libcore\result.rs:827
  12: wasi_common::sys::windows::fdentry::{{impl}}::from_raw_handle
             at C:\Users\Artur Jamro\.cargo\git\checkouts\wasi-common-a5b4696a5db11d18\93e1657\src\sys\windows\fdentry.rs:54
  13: wasi_common::sys::windows::fdentry::FdEntry::duplicate<std::io::stdio::Stdin>
             at C:\Users\Artur Jamro\.cargo\git\checkouts\wasi-common-a5b4696a5db11d18\93e1657\src\sys\windows\fdentry.rs:39
  14: wasi_common::ctx::WasiCtxBuilder::inherit_stdio
             at C:\Users\Artur Jamro\.cargo\git\checkouts\wasi-common-a5b4696a5db11d18\93e1657\src\ctx.rs:65
  15: wasmtime_wasi::instantiate::instantiate_wasi
             at .\wasmtime-wasi\src\instantiate.rs:105
  16: wasmtime::main
             at .\src\wasmtime.rs:249
  17: std::rt::lang_start::{{closure}}<()>
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\src\libstd\rt.rs:64
  18: std::rt::lang_start_internal::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\rt.rs:49
  19: std::panicking::try::do_call<closure,i32>
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:293
  20: panic_unwind::__rust_maybe_catch_panic
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libpanic_unwind\lib.rs:85
  21: std::panicking::try
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:272
  22: std::panic::catch_unwind
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panic.rs:394
  23: std::rt::lang_start_internal
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\rt.rs:48
  24: std::rt::lang_start<()>
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\src\libstd\rt.rs:64
  25: main
  26: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  27: __scrt_common_main_seh
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  28: BaseThreadInitThunk
  29: RtlUserThreadStart
error: process didn't exit successfully: `target\debug\wasmtime.exe --dir=tmp 'C:/Users/Artur Jamro/repos/wasi-demo/target/wasm32-wasi/debug/wasi-demo.wasm' tmp/a.txt tmp/b.txt` (exit code: 101)
```

After quick investigation:
- GetSecurityInfo [here](https://github.com/CraneStation/wasi-common/blob/7287767a3fd9ac9affef65d4b592beac2229f960/winx/src/file.rs#L341) returns UnknownError,
- when run as administrator, the wasmtime works; [the docs](https://docs.microsoft.com/en-us/windows/win32/api/aclapi/nf-aclapi-getsecurityinfo) say in remarks section that you need some special access,
- there's also some TODO comment [here](https://github.com/CraneStation/wasi-common/blob/7287767a3fd9ac9affef65d4b592beac2229f960/src/sys/windows/fdentry.rs#L51) stating it could be problematic

**Comment by mrowqa** [comment]
Temporary hack I did to avoid running wasmtime as an administrator: I looked [here](https://docs.microsoft.com/en-us/windows/win32/secbp/running-with-special-privileges) and then [here](https://docs.microsoft.com/en-us/windows/win32/secbp/assigning-privileges-to-an-account). The privilege I added is "Take ownership of files or other objects" - it doesn't sound like a good solution though.

**Comment by kubkon** [comment]
Hey! Thanks for submitting the issue. It’s good to see that someone started playing with wasmtime and WASI on windows! :-) Errors like these are unfortunately to be expected when running on Windows as it is still highly experimental, but nonetheless hopefully slowly progressing forward!

I was wondering if you could do me a small favour and try out your setup with this version of `wasi-common` crate: [kubkon/wasi-common@alex-rewrite](https://github.com/kubkon/wasi-common/tree/alex-rewrite). It’d be great if we checked if this branch fixes your issues for you. To swap the versions of `wasi-common` libs, all you’d need to do would be to modify the main `Cargo.toml` for `Wasmtime` and the one in `wasmtime-wasi` crate as follows:

```
wasi-common = { git=“https://github.com/kubkon/wasi-common”, branch=“alex-rewrite” }
```

If you have any questions, don’t hesitate to just drop me a line and I’ll be more than happy to help out! :-)

**Comment by mrowqa** [comment]
Hey, the mentioned branch works fine on my machine. Thanks!

**Comment by kubkon** [comment]
Awesome, thanks for checking that out, it's much appreciated! When #34 lands, would you mind if I dropped you a line so that you could verify that everything works as expected again? :-) And if it does, we could then close this issue.

**Comment by mrowqa** [comment]
Yeah, sure. Just let me know and I will check it :)

**Comment by mrowqa** [comment]
While working on https://github.com/CraneStation/wasmtime/pull/190 I needed to debug the tests. After a while, it turned out that wasmtime (branch master) fails the cargo tests using the mentioned wasi-common rewrite (rev 5238a5d, the latest compiling commit) ending up with a segmentation fault.

**Comment by tschneidereit** [comment]
@Mrowqa, which platform are you trying to run the tests on? They're known to fail on Windows, but otherwise should pass.

**Comment by kubkon** [comment]
@Mrowqa it's precisely as @tschneidereit says; the spec testsuite for `wasmtime` is known to fail on Windows currently.

**Comment by mrowqa** [comment]
I didn't know that. I ran them on the Windows. So it looks like everything's right.

**Comment by mrowqa** [comment]
> 
> 
> Awesome, thanks for checking that out, it's much appreciated! When #34 lands, would you mind if I dropped you a line so that you could verify that everything works as expected again? :-) And if it does, we could then close this issue.

I have checked the previous example with copying a file and it works now.

**Comment by kubkon** [comment]
Perfect, thanks again @Mrowqa! :-)
