### ISSUE TITLE
Ambiguous spec of __wasi_fstflags_t

### ISSUE THREAD

**Issue by marmistrz** [CraneStation/wasi-common#53]
```
Possible values:

    __WASI_FILESTAT_SET_ATIM
    Adjust the last data access timestamp to the value stored in __wasi_filestat_t::st_atim.

    __WASI_FILESTAT_SET_ATIM_NOW
    Adjust the last data access timestamp to the time of clock __WASI_CLOCK_REALTIME.

    __WASI_FILESTAT_SET_MTIM
    Adjust the last data modification timestamp to the value stored in __wasi_filestat_t::st_mtim.

    __WASI_FILESTAT_SET_MTIM_NOW
    Adjust the last data modification timestamp to the time of clock __WASI_CLOCK_REALTIME.
```

It is unclear what the behavior is, when the both flags `__WASI_FILESTAT_SET_MTIM` and `__WASI_FILESTAT_SET_MTIM_NOW` are set. Should whichever of them take precedence or should one return `EINVAL`? This should be clarified in the API docs.

I suggest we return `EINVAL`

**Comment by kubkon** [comment]
@marmistrz are you going to file an issue in [WASI issue tracker](https://github.com/WebAssembly/WASI/issues) as suggested by @sunfishcode? Or @sunfishcode will you do it? Either way, after it happens, I suggest we make references from this one to the one in WASI tracker, and close this one.

**Comment by marmistrz** [comment]
I will, tomorrow.

**Comment by marmistrz** [comment]
Closing in favor of https://github.com/CraneStation/wasmtime/issues/270
