### ISSUE TITLE
SET_ATIM in path_filestat_set_times

### ISSUE THREAD

**Issue by sunfishcode** [CraneStation/wasi-common#95]
The if-else chain here:

https://github.com/CraneStation/wasi-common/blob/master/src/sys/unix/hostcalls_impl/fs.rs#L426

checks for `set_atim_now` twice. It looks like the first condition should check `set_atim` instead, similar to the `mtim` version below it.

**Comment by kubkon** [comment]
Good catch!

**Comment by kubkon** [comment]
cc @marmistrz would you mind having a look? :-)

**Comment by marmistrz** [comment]
A bug indeed!

I'm wondering if we there's anything we can do here to make this function less error-prone, but everything I can think of just moves the repetition around.
